# Generated by Django 5.1.4 on 2024-12-26 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KAM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=40, primary_key=True, serialize=False)),
                ('Mobile', models.CharField(max_length=13)),
                ('LeadType', models.CharField(choices=[('BE', 'BinaknerExpress'), ('BB', 'BinaknerBistro'), ('BR', 'BinaknerRestaurant'), ('BC', 'BinaknerCafé'), ('BP', 'BinaknerPizzeria'), ('BB', 'BikanerWala')], max_length=2)),
                ('LeadStatus', models.CharField(choices=[('OO', 'Open'), ('OC', 'On-Call'), ('CE', 'Close'), ('DE', 'Done')], max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='Leads',
        ),
    ]
