# Generated by Django 5.1.4 on 2024-12-26 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KAM', '0002_lead_delete_leads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='LeadType',
            field=models.CharField(choices=[('BE', 'BinaknerExpress'), ('BB', 'BinaknerBistro'), ('BR', 'BinaknerRestaurant'), ('BC', 'BinaknerCafe'), ('BP', 'BinaknerPizzeria'), ('BB', 'BikanerWala')], max_length=2),
        ),
    ]
