# Generated by Django 5.1.4 on 2024-12-29 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KAM', '0003_alter_lead_leadtype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='LeadType',
            field=models.CharField(choices=[('BE', 'BikanerExpress'), ('BB', 'BikanerBistro'), ('BR', 'BikanerRestaurant'), ('BC', 'BikanerCafe'), ('BP', 'BikanerPizzeria'), ('BB', 'BikanerWale')], max_length=2),
        ),
    ]
